- defaults write com.apple.dock static-only -bool TRUE # Only show active apps
- defaults write com.apple.dock autohide-time-modifier -int 0 # Remove Dock hide / show animation
- defaults write com.apple.dock autohide -bool true # Enable Dock auto-hide
- killall Dock # Reset Dock
- open https://goo.gl/6fMg2D # Redirect to a link enable switch between windows
