installations:
    cask:
        - atom
    apm:
        - vim-mode-plus
        - language-blade
        - language-vue
        - editorconfig
        - blame
        - emmet
        - file-icons

configurations: ~

symlinks:Â ~
