installations: ~

configurations:
    - git config --global user.name "Steven Yung"
    - git config --global user.email stevenyung@icloud.com

    # Setup vi as default editor
    - git config --global core.editor vi

symlinks: ~
